# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1146, 896)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statusLEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.statusLEdit.setObjectName("statusLEdit")
        self.horizontalLayout.addWidget(self.statusLEdit)
        self.reconnectPButt = QtWidgets.QPushButton(self.centralwidget)
        self.reconnectPButt.setObjectName("reconnectPButt")
        self.horizontalLayout.addWidget(self.reconnectPButt)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.dataGBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataGBox.sizePolicy().hasHeightForWidth())
        self.dataGBox.setSizePolicy(sizePolicy)
        self.dataGBox.setMinimumSize(QtCore.QSize(400, 0))
        self.dataGBox.setObjectName("dataGBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dataGBox)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dataGView = QtWidgets.QGraphicsView(self.dataGBox)
        self.dataGView.setObjectName("dataGView")
        self.gridLayout_3.addWidget(self.dataGView, 0, 0, 1, 3)
        self.channelDataTWidget = QtWidgets.QTableWidget(self.dataGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelDataTWidget.sizePolicy().hasHeightForWidth())
        self.channelDataTWidget.setSizePolicy(sizePolicy)
        self.channelDataTWidget.setMinimumSize(QtCore.QSize(600, 200))
        self.channelDataTWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.channelDataTWidget.setFont(font)
        self.channelDataTWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.channelDataTWidget.setRowCount(0)
        self.channelDataTWidget.setColumnCount(0)
        self.channelDataTWidget.setObjectName("channelDataTWidget")
        self.channelDataTWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.channelDataTWidget.horizontalHeader().setDefaultSectionSize(120)
        self.channelDataTWidget.horizontalHeader().setHighlightSections(False)
        self.channelDataTWidget.horizontalHeader().setMinimumSectionSize(60)
        self.channelDataTWidget.horizontalHeader().setSortIndicatorShown(False)
        self.channelDataTWidget.horizontalHeader().setStretchLastSection(False)
        self.channelDataTWidget.verticalHeader().setDefaultSectionSize(30)
        self.channelDataTWidget.verticalHeader().setMinimumSectionSize(25)
        self.channelDataTWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.channelDataTWidget, 1, 0, 4, 3)
        self.gridLayout.addWidget(self.dataGBox, 0, 1, 1, 2)
        self.controlGBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlGBox.sizePolicy().hasHeightForWidth())
        self.controlGBox.setSizePolicy(sizePolicy)
        self.controlGBox.setMinimumSize(QtCore.QSize(300, 0))
        self.controlGBox.setObjectName("controlGBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.controlGBox)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 14, 0, 1, 2)
        self.graphResetPButt = QtWidgets.QPushButton(self.controlGBox)
        self.graphResetPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.graphResetPButt.setObjectName("graphResetPButt")
        self.gridLayout_2.addWidget(self.graphResetPButt, 26, 1, 1, 1)
        self.readParametersPButton = QtWidgets.QPushButton(self.controlGBox)
        self.readParametersPButton.setMinimumSize(QtCore.QSize(0, 30))
        self.readParametersPButton.setObjectName("readParametersPButton")
        self.gridLayout_2.addWidget(self.readParametersPButton, 24, 1, 1, 1)
        self.cycleMeasPButt = QtWidgets.QPushButton(self.controlGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cycleMeasPButt.sizePolicy().hasHeightForWidth())
        self.cycleMeasPButt.setSizePolicy(sizePolicy)
        self.cycleMeasPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.cycleMeasPButt.setObjectName("cycleMeasPButt")
        self.gridLayout_2.addWidget(self.cycleMeasPButt, 3, 1, 1, 1)
        self.logRestartPButt = QtWidgets.QPushButton(self.controlGBox)
        self.logRestartPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.logRestartPButt.setObjectName("logRestartPButt")
        self.gridLayout_2.addWidget(self.logRestartPButt, 26, 0, 1, 1)
        self.cycleReadPButton = QtWidgets.QPushButton(self.controlGBox)
        self.cycleReadPButton.setMinimumSize(QtCore.QSize(0, 30))
        self.cycleReadPButton.setObjectName("cycleReadPButton")
        self.gridLayout_2.addWidget(self.cycleReadPButton, 10, 1, 1, 1)
        self.itbParametersTWidget = QtWidgets.QTableWidget(self.controlGBox)
        self.itbParametersTWidget.setRowCount(0)
        self.itbParametersTWidget.setColumnCount(2)
        self.itbParametersTWidget.setObjectName("itbParametersTWidget")
        item = QtWidgets.QTableWidgetItem()
        self.itbParametersTWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itbParametersTWidget.setHorizontalHeaderItem(1, item)
        self.itbParametersTWidget.horizontalHeader().setStretchLastSection(False)
        self.itbParametersTWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.itbParametersTWidget, 23, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.controlGBox)
        self.line.setMinimumSize(QtCore.QSize(0, 5))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 13, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.controlGBox)
        self.line_2.setMinimumSize(QtCore.QSize(0, 5))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 25, 0, 1, 2)
        self.singleReadPButton = QtWidgets.QPushButton(self.controlGBox)
        self.singleReadPButton.setMinimumSize(QtCore.QSize(0, 30))
        self.singleReadPButton.setObjectName("singleReadPButton")
        self.gridLayout_2.addWidget(self.singleReadPButton, 10, 0, 1, 1)
        self.writeParametersPButton = QtWidgets.QPushButton(self.controlGBox)
        self.writeParametersPButton.setMinimumSize(QtCore.QSize(0, 30))
        self.writeParametersPButton.setObjectName("writeParametersPButton")
        self.gridLayout_2.addWidget(self.writeParametersPButton, 24, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.controlGBox)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cycleReadPeriodLabel = QtWidgets.QLabel(self.controlGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cycleReadPeriodLabel.sizePolicy().hasHeightForWidth())
        self.cycleReadPeriodLabel.setSizePolicy(sizePolicy)
        self.cycleReadPeriodLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.cycleReadPeriodLabel.setObjectName("cycleReadPeriodLabel")
        self.horizontalLayout_2.addWidget(self.cycleReadPeriodLabel)
        self.cycleReadPeriodSBox = QtWidgets.QSpinBox(self.controlGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cycleReadPeriodSBox.sizePolicy().hasHeightForWidth())
        self.cycleReadPeriodSBox.setSizePolicy(sizePolicy)
        self.cycleReadPeriodSBox.setMinimumSize(QtCore.QSize(50, 30))
        self.cycleReadPeriodSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cycleReadPeriodSBox.setMinimum(1)
        self.cycleReadPeriodSBox.setMaximum(3600)
        self.cycleReadPeriodSBox.setObjectName("cycleReadPeriodSBox")
        self.horizontalLayout_2.addWidget(self.cycleReadPeriodSBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 11, 0, 1, 2)
        self.stopMeasPButt = QtWidgets.QPushButton(self.controlGBox)
        self.stopMeasPButt.setObjectName("stopMeasPButt")
        self.gridLayout_2.addWidget(self.stopMeasPButt, 4, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.controlGBox)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 9, 0, 1, 2)
        self.singleMeasPButt = QtWidgets.QPushButton(self.controlGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleMeasPButt.sizePolicy().hasHeightForWidth())
        self.singleMeasPButt.setSizePolicy(sizePolicy)
        self.singleMeasPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.singleMeasPButt.setObjectName("singleMeasPButt")
        self.gridLayout_2.addWidget(self.singleMeasPButt, 3, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.controlGBox)
        self.line_4.setMinimumSize(QtCore.QSize(0, 5))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 20, 0, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.controlGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.dac1VoltageSBox = QtWidgets.QDoubleSpinBox(self.controlGBox)
        self.dac1VoltageSBox.setMinimumSize(QtCore.QSize(50, 30))
        self.dac1VoltageSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dac1VoltageSBox.setMaximum(30.0)
        self.dac1VoltageSBox.setSingleStep(0.1)
        self.dac1VoltageSBox.setObjectName("dac1VoltageSBox")
        self.gridLayout_4.addWidget(self.dac1VoltageSBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.controlGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.dac2VoltageSBox = QtWidgets.QDoubleSpinBox(self.controlGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dac2VoltageSBox.sizePolicy().hasHeightForWidth())
        self.dac2VoltageSBox.setSizePolicy(sizePolicy)
        self.dac2VoltageSBox.setMinimumSize(QtCore.QSize(50, 30))
        self.dac2VoltageSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dac2VoltageSBox.setMaximum(30.0)
        self.dac2VoltageSBox.setSingleStep(0.1)
        self.dac2VoltageSBox.setObjectName("dac2VoltageSBox")
        self.gridLayout_4.addWidget(self.dac2VoltageSBox, 2, 1, 1, 1)
        self.dacVoltageSetPButton = QtWidgets.QPushButton(self.controlGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dacVoltageSetPButton.sizePolicy().hasHeightForWidth())
        self.dacVoltageSetPButton.setSizePolicy(sizePolicy)
        self.dacVoltageSetPButton.setMinimumSize(QtCore.QSize(0, 60))
        self.dacVoltageSetPButton.setObjectName("dacVoltageSetPButton")
        self.gridLayout_4.addWidget(self.dacVoltageSetPButton, 0, 2, 3, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 19, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.controlGBox)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 16, 0, 1, 2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.kuSBox = QtWidgets.QSpinBox(self.controlGBox)
        self.kuSBox.setObjectName("kuSBox")
        self.gridLayout_5.addWidget(self.kuSBox, 1, 1, 1, 1)
        self.zeroSignalSBox = QtWidgets.QSpinBox(self.controlGBox)
        self.zeroSignalSBox.setObjectName("zeroSignalSBox")
        self.gridLayout_5.addWidget(self.zeroSignalSBox, 1, 2, 1, 1)
        self.chanSBox = QtWidgets.QSpinBox(self.controlGBox)
        self.chanSBox.setObjectName("chanSBox")
        self.gridLayout_5.addWidget(self.chanSBox, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.controlGBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.controlGBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.controlGBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 7, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.controlGBox)
        self.line_3.setMinimumSize(QtCore.QSize(0, 5))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 15, 0, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.controlGBox)
        self.line_5.setMinimumSize(QtCore.QSize(0, 5))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 8, 0, 1, 2)
        self.dbgPButton = QtWidgets.QPushButton(self.controlGBox)
        self.dbgPButton.setObjectName("dbgPButton")
        self.gridLayout_2.addWidget(self.dbgPButton, 6, 0, 1, 2)
        self.line_6 = QtWidgets.QFrame(self.controlGBox)
        self.line_6.setMinimumSize(QtCore.QSize(0, 5))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 5, 0, 1, 2)
        self.gridLayout.addWidget(self.controlGBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1146, 30))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.configOpenQAction = QtWidgets.QAction(MainWindow)
        self.configOpenQAction.setObjectName("configOpenQAction")
        self.configSaveQAction = QtWidgets.QAction(MainWindow)
        self.configSaveQAction.setObjectName("configSaveQAction")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.configOpenQAction)
        self.menu.addAction(self.configSaveQAction)
        self.menu.addSeparator()
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ИТБ Клиент"))
        self.reconnectPButt.setText(_translate("MainWindow", "Переподключение"))
        self.dataGBox.setTitle(_translate("MainWindow", "Данные"))
        self.controlGBox.setTitle(_translate("MainWindow", "Управление"))
        self.graphResetPButt.setText(_translate("MainWindow", "Перезапуск графика"))
        self.readParametersPButton.setText(_translate("MainWindow", "Прочитать"))
        self.cycleMeasPButt.setText(_translate("MainWindow", "Циклический"))
        self.logRestartPButt.setText(_translate("MainWindow", "Перезапуск лог-файла"))
        self.cycleReadPButton.setText(_translate("MainWindow", "Циклическое - Старт"))
        item = self.itbParametersTWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Наименование"))
        item = self.itbParametersTWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значение"))
        self.singleReadPButton.setText(_translate("MainWindow", "Разовое"))
        self.writeParametersPButton.setText(_translate("MainWindow", "Записать"))
        self.label_4.setText(_translate("MainWindow", "Запуск измерения"))
        self.cycleReadPeriodLabel.setText(_translate("MainWindow", "Интервал циклического чтения, с"))
        self.stopMeasPButt.setText(_translate("MainWindow", "Остановить"))
        self.label_6.setText(_translate("MainWindow", "Чтение"))
        self.singleMeasPButt.setText(_translate("MainWindow", "Единичный"))
        self.label_2.setText(_translate("MainWindow", "U подложки, В"))
        self.label_3.setText(_translate("MainWindow", "U ЦАП2, В"))
        self.dacVoltageSetPButton.setText(_translate("MainWindow", "Установить"))
        self.label.setText(_translate("MainWindow", "Параметры измерений"))
        self.label_5.setText(_translate("MainWindow", "№ канала"))
        self.label_7.setText(_translate("MainWindow", "КУ, битовое"))
        self.label_8.setText(_translate("MainWindow", "Ноль/сигнал"))
        self.dbgPButton.setText(_translate("MainWindow", "Отладка"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.configOpenQAction.setText(_translate("MainWindow", "Открыть"))
        self.configSaveQAction.setText(_translate("MainWindow", "Сохранить"))
        self.action_3.setText(_translate("MainWindow", "ДНТ по умолчанию"))
